lsp: Fix Position on hover
The Position on hover was causing the following failure:

      File ".venv/lib/python3.10/site-packages/sphinx_needs/lsp/esbonio.py", line 264, in get_need_type_and_id
        word = get_word(ls, params)
      File ".venv/lib/python3.10/site-packages/sphinx_needs/lsp/esbonio.py", line 245, in get_word
        line_no, col = params.position
    TypeError: cannot unpack non-iterable Position object

The params.position object isn't iterable, however, it does define
attributes like .line and .character that can be used.